baba@LAPTOP-A6A7D962:~/experiment-report/202401/0105/dynamic_error_example$ cargo run
   Compiling dynamic_error_example v0.1.0 (/home/baba/experiment-report/202401/0105/dynamic_error_example)
warning: unused import: `thread_rng`
 --> src/main.rs:3:17
  |
3 | use rand::{Rng, thread_rng};
  |                 ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: variable does not need to be mutable
  --> src/main.rs:11:9
   |
11 |     let mut h = RefMut::new(String::from("Hello"));
   |         ----^
   |         |
   |         help: remove this `mut`
   |
   = note: `#[warn(unused_mut)]` on by default

warning: variable does not need to be mutable
  --> src/main.rs:12:9
   |
12 |     let mut w = RefMut::new(String::from("World"));
   |         ----^
   |         |
   |         help: remove this `mut`

warning: `dynamic_error_example` (bin "dynamic_error_example") generated 3 warnings (run `cargo fix --bin "dynamic_error_example"` to apply 3 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 0.74s
     Running `target/debug/dynamic_error_example`
World
World
World
Hello
thread 'main' panicked at /home/baba/experiment-report/202401/0105/dynamic_error_example/src/lib.rs:72:17:
cannot back to mut
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
baba@LAPTOP-A6A7D962:~/experiment-report/202401/0105/dynamic_error_example$